name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - head
        os:
          - "ubuntu-22.04"
          - "ubuntu-20.04"
          - "macos-12"
          - "macos-11"
    continue-on-error: ${{ matrix.ruby == 'head' }}
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rake
